=== IsraelGit13/mi-primer-formulario-en-HTML/EAC02/activitat_03/activitat_3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="series_escandinaves">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="serie" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string"/>
                            <xs:element name="temporades" type="xs:integer"/>
                            <xs:element name="actors">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="actor" maxOccurs="5" minOccurs="1" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="pais" type="xs:string"/>
                            <xs:element name="any_inici">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1900"/> 
                                        <xs:maxExclusive value="2000"/> 
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="sinopsi" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="categoria" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Policial"/>
                                    <xs:enumeration value="Suspense"/>
                                    <xs:enumeration value="PolÃ­tic"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="durada_capitol" type="xs:integer" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== IsraelGit13/mi-primer-formulario-en-HTML/EAC02/activitat_03/avtivitat_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<series_escandinaves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="activitat_3.xsd">
    <serie categoria="Policial" durada_capitol="45">
        <nom>Atrapats</nom>
        <temporades>3</temporades>
        <actors>
            <actor>Ólafur Darri</actor>
            <actor>Ilmur Kristjánsdóttir</actor>
        </actors>
        <pais>Islàndia</pais>
        <any_inici>1999</any_inici> <!-- Cambiado a 1999 -->
        <sinopsi>Descripción de la serie.</sinopsi>
    </serie>
    <serie categoria="Suspense">
        <nom>Deadwind</nom>
        <temporades>3</temporades>
        <actors>
            <actor>Pihla Viitala</actor>
        </actors>
        <pais>Finlàndia</pais>
        <any_inici>1998</any_inici> 
        <sinopsi>Descripción de la serie.</sinopsi>
    </serie>
    <serie categoria="Policial">
        <nom>Wallander</nom>
        <temporades>3</temporades>
        <actors>
            <actor>Krister Henriksson</actor>
            <actor>Johanna Sällström</actor>
        </actors>
        <pais>Suecia</pais>
        <any_inici>1997</any_inici> 
        <sinopsi>Descripción de la serie.</sinopsi>
    </serie>
    <serie categoria="Polític">
        <nom>Borgen</nom>
        <temporades>4</temporades>
        <actors>
            <actor>Sidse Babett</actor>
            <actor>Birgitte Hjort</actor>
        </actors>
        <pais>Dinamarca</pais>
        <any_inici>1995</any_inici> 
        <sinopsi>Descripción de la serie.</sinopsi>
    </serie>
    <serie categoria="Suspense">
        <nom>El puente</nom>
        <temporades>1</temporades>
        <actors>
            <actor>Nombre Actor</actor>
        </actors>
        <pais>Dinamarca</pais>
        <any_inici>1996</any_inici> 
        <sinopsi>Descripción de la serie.</sinopsi>
    </serie>
</series_escandinaves>
